version: '3.5'
services:
  webapp:
    container_name: webapp
    restart: always
    image: 888507318922.dkr.ecr.ap-south-1.amazonaws.com/cloud-instance-manager:latest
    ports:
     - 5000:5000  
    env_file: .env

  database:
    image: "postgres"
    env_file: .env
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data/
    

  migration:
    image: 888507318922.dkr.ecr.ap-south-1.amazonaws.com/cloud-instance-manager:latest
    env_file: .env
    command: /bin/bash -c "sleep 5 && python manage.py db upgrade"
    depends_on: 
      - database
    restart: on-failure
    

  dumpAdminData:
    image: 888507318922.dkr.ecr.ap-south-1.amazonaws.com/cloud-instance-manager:latest
    env_file: .env
    command: /bin/bash -c "sleep 6 && python dump_admin_record.py"
    depends_on: 
      - database
      - migration


volumes:
  postgres-data:
